version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
  db:
    image: mysql
    container_name: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd